export const MEDIA_SET_MEDIA_DATA = 'MEDIA_SET_MEDIA_DATA';
export const MEDIA_SET_GENRES = 'MEDIA_SET_GENRES';

export const MEDIA_SET_MEDIA_TYPE = 'MEDIA_SET_MEDIA_TYPE';
export const MEDIA_SET_TIME_WINDOW = 'MEDIA_SET_TIME_WINDOW';
export const MEDIA_SET_PAGE = 'MEDIA_SET_PAGE';
export const MEDIA_ACTIVE_GENRE = 'MEDIA_ACTIVE_GENRE';
